# Vector - Matrix - Tensor

In [15]:
import numpy as np

In [16]:
# Nhập từ bàn phím 2 vector numpy a, b có cùng kích thước n.
n = 2

# A = np.array(list(map(float, input().split())))
# B = np.array(list(map(float, input().split())))

A = np.array([1, 2])
B = np.array([3, 4])

In [17]:
# In ra max, min, giá trị trung bình, độ lệch chuẩn của vector, giá trị trung vị của A
maximum = np.max(A)
minimum = np.min(A)
mean = np.mean(A)
std_dev = np.std(A)
median = np.median(A)

print("Maximum:", maximum)
print("Minimum:", minimum)
print("Mean:", mean)
print("Standard Deviation:", std_dev)
print("Median:", median)


Maximum: 2
Minimum: 1
Mean: 1.5
Standard Deviation: 0.5
Median: 1.5


In [18]:
# Tạo 1 ma trận numpy c (2-D) có kích thước nx2 từ a, b, in ra màn hình.
C = np.array((A, B))
C

array([[1, 2],
       [3, 4]])

In [20]:
# Khởi tạo 1 ma trận (2-D) numpy d với kích thước nxn theo phân phối Gauss (với mean, std của b), in kết quả ra màn hình.
mean = np.mean(B)
std_dev = np.std(B)

D = np.random.normal(mean, std_dev, size=(n, n))
D

array([[3.2087656 , 3.7368796 ],
       [3.57293386, 3.69759733]])

In [23]:
#Tính tổng, hiệu, tích 2 ma trận, tích ma trận chuyển vị  của d với ma trận nghịch đảo của d.

D_T = np.transpose(D) # transpose of D
D_I = np.linalg.inv(D) # inverse of D

# Calculate the sum of two matrices
sum_matrix = D_T + D_I

# Calculate the difference of two matrices
diff_matrix = D_T - D_I

# Calculate the product of two matrices
product_matrix = np.dot(D_T, D_I)

print("Sum of two matrices:\n", sum_matrix)
print("Difference of two matrices:\n", diff_matrix)
print("Product of two matrices:\n", product_matrix)


Sum of two matrices:
 [[0.72198371 6.08613465]
 [6.13982033 1.5395743 ]]
Difference of two matrices:
 [[5.69554749 1.05973308]
 [1.33393887 5.85562036]]
Product of two matrices:
 [[ 0.60604812  0.35379867]
 [-0.40769728  1.41202855]]


In [36]:
# Chuyển ma trận c về tensor numpy e (3-D) (nếu không đủ dữ liệu để chuyển về 3-D thì thêm dữ liệu), in ra màn hình.
# Assuming c is the matrix you want to convert to a 3-D tensor
c = np.array([[1, 2], [3, 4]])

e = np.expand_dims(c, axis=2)
print("Tensor e (3-D):")
print(e.shape)
print(e)

Tensor e (3-D):
(2, 2, 1)
[[[1]
  [2]]

 [[3]
  [4]]]


https://nttuan8.com/bai-1-tensor/