# Numpy Array Creating 

In [57]:
import numpy as np

### Khởi tạo một mảng numpy nguyên a (1-D) với n phần tử ngẫu nhiên trong khoảng từ [1, 14].

In [58]:
n = 10 # number of elements
arr = np.random.randint(1, 15, size= n)

In [59]:
print("Original array:")
display(arr)
print("ndim: ", arr.ndim)
print("shape: ", arr.shape)
print("len: ", len(arr))
print("dtype: ", arr.dtype)
print("itemsize: ", arr.itemsize)

Original array:


array([11,  2,  3,  6, 11, 11,  2, 14,  7,  1])

ndim:  1
shape:  (10,)
len:  10
dtype:  int32
itemsize:  4


### Khởi tạo 1 mảng numpy b với 100 số chẵn đầu tiên.

In [60]:
arr = np.arange(0, 200, 2)

In [61]:
print("Original array:")
display(arr)
print("ndim: ", arr.ndim)
print("shape: ", arr.shape)
print("len: ", len(arr))
print("dtype: ", arr.dtype)
print("itemsize: ", arr.itemsize)

Original array:


array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

ndim:  1
shape:  (100,)
len:  100
dtype:  int32
itemsize:  4


### Khởi tạo 1 ma trận numpy c có kích thước nxn với 100 phần tử 0, in ra màn hình.

In [62]:
n = int(100 ** (1/2))

arr = np.zeros((n,n))

In [63]:
print("Original array:")
display(arr)
print("ndim: ", arr.ndim)
print("shape: ", arr.shape)
print("len: ", len(arr))
print("dtype: ", arr.dtype)
print("itemsize: ", arr.itemsize)

Original array:


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

ndim:  2
shape:  (10, 10)
len:  10
dtype:  float64
itemsize:  8


### Khởi tạo ma trận đơn vị d có kích thước nxn.


In [64]:
n = 5

arr = np.eye(n)

In [65]:
print("Original array:")
display(arr)
print("ndim: ", arr.ndim)
print("shape: ", arr.shape)
print("len: ", len(arr))
print("dtype: ", arr.dtype)
print("itemsize: ", arr.itemsize)

Original array:


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

ndim:  2
shape:  (5, 5)
len:  5
dtype:  float64
itemsize:  8


### Khởi tạo ma trận đường chéo e với các giá trị trên đường chéo là mảng a.

In [66]:
arr = np.arange(0, 10, 2)
e = np.diag(arr)

In [67]:
print("Array arr:")
display(arr)
print("Array e:")
display(e)
print("ndim: ", e.ndim)
print("shape: ", e.shape)
print("len: ", len(e))
print("dtype: ", e.dtype)
print("itemsize: ", e.itemsize)

Array arr:


array([0, 2, 4, 6, 8])

Array e:


array([[0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 8]])

ndim:  2
shape:  (5, 5)
len:  5
dtype:  int32
itemsize:  4
