# Quản lý điểm với Numpy

In [1]:
import numpy as np

In [2]:
# Lập 1 mảng 2 chiều lưu lần lượt điểm đại số tuyến tính, 
# xác suất thống kê, giải tích với 20 phần tử mỗi hàng random trong khoảng từ [0, 10].

scores = np.random.randint(0, 11, (3, 20))
display(scores)

array([[ 1,  3,  4, 10,  8, 10,  2,  0,  5,  0,  5,  1,  3,  1,  5,  8,
         5,  5,  6,  4],
       [10,  4,  2,  7,  1,  4,  1,  3,  0,  9,  4,  0,  9,  6,  8,  9,
         9, 10,  9,  1],
       [ 5,  5,  2,  7,  4,  1,  6,  3,  2,  5,  3, 10, 10,  4, 10,  5,
        10,  3, 10,  1]])

In [3]:
# In ra giá vị trí điểm lớn nhất và nhỏ nhất ở mỗi môn.
# max_scores = np.max(scores, axis=1)
# min_scores = np.min(scores, axis=1)

# display("Maximum scores in each subject:", max_scores)
# display("Minimum scores in each subject:", min_scores)

for index, subject in enumerate(scores):
    print("Mon hoc ", index + 1)
    print("Diem thap nhat: ", np.min(subject))
    print("Diem cao nhat: ", np.max(subject))
    print()

Mon hoc  1
Diem thap nhat:  0
Diem cao nhat:  10

Mon hoc  2
Diem thap nhat:  0
Diem cao nhat:  10

Mon hoc  3
Diem thap nhat:  1
Diem cao nhat:  10



In [4]:
# Làm phẳng mảng và xóa đi các vị trí có điểm là 0, in ra màn hình.

flat_scores = scores.flatten()
flat_scores = flat_scores[flat_scores != 0]
display(flat_scores)

array([ 1,  3,  4, 10,  8, 10,  2,  5,  5,  1,  3,  1,  5,  8,  5,  5,  6,
        4, 10,  4,  2,  7,  1,  4,  1,  3,  9,  4,  9,  6,  8,  9,  9, 10,
        9,  1,  5,  5,  2,  7,  4,  1,  6,  3,  2,  5,  3, 10, 10,  4, 10,
        5, 10,  3, 10,  1])

In [5]:
# Sắp xếp giảm theo thuật toán quicksort, in ra màn hình.
sorted_scores = np.sort(flat_scores)[::-1]
display(sorted_scores)

array([10, 10, 10, 10, 10, 10, 10, 10, 10,  9,  9,  9,  9,  9,  8,  8,  8,
        7,  7,  6,  6,  6,  5,  5,  5,  5,  5,  5,  5,  5,  5,  4,  4,  4,
        4,  4,  4,  4,  3,  3,  3,  3,  3,  3,  2,  2,  2,  2,  1,  1,  1,
        1,  1,  1,  1,  1])

In [6]:
# Hàm search_sorted chỉ đúng với các số tăng dần, nên cần sắp xếp lại mảng điểm tăng dần.
sorted_scores = sorted_scores[::-1]

In [8]:
# Nhập vào một số thực k từ bàn phím và cho biết vị trí chèn k vào mảng mà không phá vỡ tính sắp xếp của mảng và thêm vào vị trí đó.
k = int(input("Nhap vao so thuc k: "))  
insert_index = np.searchsorted(sorted_scores, k, side='right')
print(insert_index)
sorted_scores = np.insert(sorted_scores, insert_index, k)
display(sorted_scores[::-1])

18


array([10, 10, 10, 10, 10, 10, 10, 10, 10,  9,  9,  9,  9,  9,  8,  8,  8,
        7,  7,  6,  6,  6,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  4,  4,
        4,  4,  4,  4,  4,  3,  3,  3,  3,  3,  3,  3,  2,  2,  2,  2,  1,
        1,  1,  1,  1,  1,  1,  1])